// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/ArticleModel.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 9044507090241329163),
      name: 'ArticleModel',
      lastPropertyId: const obx_int.IdUid(8, 274959432619075919),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4042092603483280900),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9032401650778124531),
            name: 'author',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3828757692747197045),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 282119614763544580),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5615380863390379944),
            name: 'url',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8722359345148164459),
            name: 'urlToImage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4728800492768223803),
            name: 'publishedAt',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 274959432619075919),
            name: 'content',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 9044507090241329163),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [5103352539499801872],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        2689281904502876999,
        4780296232519718900,
        4707417839400428472,
        3091448847628443179,
        921553035367680076,
        3432131316637175413,
        6094303387663193542,
        8166119680289049355
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ArticleModel: obx_int.EntityDefinition<ArticleModel>(
        model: _entities[0],
        toOneRelations: (ArticleModel object) => [],
        toManyRelations: (ArticleModel object) => {},
        getId: (ArticleModel object) => object.id,
        setId: (ArticleModel object, int id) {
          object.id = id;
        },
        objectToFB: (ArticleModel object, fb.Builder fbb) {
          final authorOffset =
              object.author == null ? null : fbb.writeString(object.author!);
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final urlOffset =
              object.url == null ? null : fbb.writeString(object.url!);
          final urlToImageOffset = object.urlToImage == null
              ? null
              : fbb.writeString(object.urlToImage!);
          final publishedAtOffset = object.publishedAt == null
              ? null
              : fbb.writeString(object.publishedAt!);
          final contentOffset =
              object.content == null ? null : fbb.writeString(object.content!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, authorOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addOffset(4, urlOffset);
          fbb.addOffset(5, urlToImageOffset);
          fbb.addOffset(6, publishedAtOffset);
          fbb.addOffset(7, contentOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final authorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final urlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final urlToImageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final publishedAtParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final object = ArticleModel(
              id: idParam,
              author: authorParam,
              title: titleParam,
              description: descriptionParam,
              url: urlParam,
              urlToImage: urlToImageParam,
              publishedAt: publishedAtParam,
              content: contentParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ArticleModel] entity fields to define ObjectBox queries.
class ArticleModel_ {
  /// See [ArticleModel.id].
  static final id =
      obx.QueryIntegerProperty<ArticleModel>(_entities[0].properties[0]);

  /// See [ArticleModel.author].
  static final author =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[1]);

  /// See [ArticleModel.title].
  static final title =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[2]);

  /// See [ArticleModel.description].
  static final description =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[3]);

  /// See [ArticleModel.url].
  static final url =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[4]);

  /// See [ArticleModel.urlToImage].
  static final urlToImage =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[5]);

  /// See [ArticleModel.publishedAt].
  static final publishedAt =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[6]);

  /// See [ArticleModel.content].
  static final content =
      obx.QueryStringProperty<ArticleModel>(_entities[0].properties[7]);
}
